package com.begoit.mooc.db;

import java.util.List;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.query.Query;
import org.greenrobot.greendao.query.QueryBuilder;

import com.begoit.mooc.offline.entity.course.course_detail.course_files.ArticleClassEntity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "ARTICLE_CLASS_ENTITY".
*/
public class ArticleClassEntityDao extends AbstractDao<ArticleClassEntity, String> {

    public static final String TABLENAME = "ARTICLE_CLASS_ENTITY";

    /**
     * Properties of entity ArticleClassEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, String.class, "id", true, "ID");
        public final static Property ChannelId = new Property(1, String.class, "channelId", false, "CHANNEL_ID");
        public final static Property ChapterName = new Property(2, String.class, "chapterName", false, "CHAPTER_NAME");
        public final static Property ChapterPosition = new Property(3, String.class, "chapterPosition", false, "CHAPTER_POSITION");
        public final static Property Sort = new Property(4, String.class, "sort", false, "SORT");
    }

    private DaoSession daoSession;

    private Query<ArticleClassEntity> courseDetailFilesEntity_ArticleClassQuery;

    public ArticleClassEntityDao(DaoConfig config) {
        super(config);
    }
    
    public ArticleClassEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"ARTICLE_CLASS_ENTITY\" (" + //
                "\"ID\" TEXT PRIMARY KEY NOT NULL ," + // 0: id
                "\"CHANNEL_ID\" TEXT NOT NULL ," + // 1: channelId
                "\"CHAPTER_NAME\" TEXT," + // 2: chapterName
                "\"CHAPTER_POSITION\" TEXT," + // 3: chapterPosition
                "\"SORT\" TEXT);"); // 4: sort
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"ARTICLE_CLASS_ENTITY\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ArticleClassEntity entity) {
        stmt.clearBindings();
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(1, id);
        }
        stmt.bindString(2, entity.getChannelId());
 
        String chapterName = entity.getChapterName();
        if (chapterName != null) {
            stmt.bindString(3, chapterName);
        }
 
        String chapterPosition = entity.getChapterPosition();
        if (chapterPosition != null) {
            stmt.bindString(4, chapterPosition);
        }
 
        String sort = entity.getSort();
        if (sort != null) {
            stmt.bindString(5, sort);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ArticleClassEntity entity) {
        stmt.clearBindings();
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(1, id);
        }
        stmt.bindString(2, entity.getChannelId());
 
        String chapterName = entity.getChapterName();
        if (chapterName != null) {
            stmt.bindString(3, chapterName);
        }
 
        String chapterPosition = entity.getChapterPosition();
        if (chapterPosition != null) {
            stmt.bindString(4, chapterPosition);
        }
 
        String sort = entity.getSort();
        if (sort != null) {
            stmt.bindString(5, sort);
        }
    }

    @Override
    protected final void attachEntity(ArticleClassEntity entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    @Override
    public ArticleClassEntity readEntity(Cursor cursor, int offset) {
        ArticleClassEntity entity = new ArticleClassEntity( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // id
            cursor.getString(offset + 1), // channelId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // chapterName
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // chapterPosition
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4) // sort
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ArticleClassEntity entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setChannelId(cursor.getString(offset + 1));
        entity.setChapterName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setChapterPosition(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setSort(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
     }
    
    @Override
    protected final String updateKeyAfterInsert(ArticleClassEntity entity, long rowId) {
        return entity.getId();
    }
    
    @Override
    public String getKey(ArticleClassEntity entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(ArticleClassEntity entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "articleClass" to-many relationship of CourseDetailFilesEntity. */
    public List<ArticleClassEntity> _queryCourseDetailFilesEntity_ArticleClass(String channelId) {
        synchronized (this) {
            if (courseDetailFilesEntity_ArticleClassQuery == null) {
                QueryBuilder<ArticleClassEntity> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.ChannelId.eq(null));
                courseDetailFilesEntity_ArticleClassQuery = queryBuilder.build();
            }
        }
        Query<ArticleClassEntity> query = courseDetailFilesEntity_ArticleClassQuery.forCurrentThread();
        query.setParameter(0, channelId);
        return query.list();
    }

}
