package com.begoit.mooc.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.begoit.mooc.offline.entity.course.course_list.CourseListEntity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "COURSE_LIST_ENTITY".
*/
public class CourseListEntityDao extends AbstractDao<CourseListEntity, Void> {

    public static final String TABLENAME = "COURSE_LIST_ENTITY";

    /**
     * Properties of entity CourseListEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, long.class, "id", false, "ID");
        public final static Property ImgUrl = new Property(1, int.class, "imgUrl", false, "IMG_URL");
        public final static Property Name = new Property(2, String.class, "name", false, "NAME");
        public final static Property SchoolName = new Property(3, String.class, "schoolName", false, "SCHOOL_NAME");
    }


    public CourseListEntityDao(DaoConfig config) {
        super(config);
    }
    
    public CourseListEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"COURSE_LIST_ENTITY\" (" + //
                "\"ID\" INTEGER NOT NULL ," + // 0: id
                "\"IMG_URL\" INTEGER NOT NULL ," + // 1: imgUrl
                "\"NAME\" TEXT," + // 2: name
                "\"SCHOOL_NAME\" TEXT);"); // 3: schoolName
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"COURSE_LIST_ENTITY\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, CourseListEntity entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
        stmt.bindLong(2, entity.getImgUrl());
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(3, name);
        }
 
        String schoolName = entity.getSchoolName();
        if (schoolName != null) {
            stmt.bindString(4, schoolName);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, CourseListEntity entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
        stmt.bindLong(2, entity.getImgUrl());
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(3, name);
        }
 
        String schoolName = entity.getSchoolName();
        if (schoolName != null) {
            stmt.bindString(4, schoolName);
        }
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public CourseListEntity readEntity(Cursor cursor, int offset) {
        CourseListEntity entity = new CourseListEntity( //
            cursor.getLong(offset + 0), // id
            cursor.getInt(offset + 1), // imgUrl
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // name
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // schoolName
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, CourseListEntity entity, int offset) {
        entity.setId(cursor.getLong(offset + 0));
        entity.setImgUrl(cursor.getInt(offset + 1));
        entity.setName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setSchoolName(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(CourseListEntity entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(CourseListEntity entity) {
        return null;
    }

    @Override
    public boolean hasKey(CourseListEntity entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
