package com.begoit.mooc.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.begoit.mooc.offline.entity.course.course_detail.CourseDetailEntity;
import com.begoit.mooc.offline.entity.course.course_detail.course_files.ArticelEntity;
import com.begoit.mooc.offline.entity.course.course_detail.course_files.ArticleClassEntity;
import com.begoit.mooc.offline.entity.course.course_detail.course_files.CourseDetailFilesEntity;
import com.begoit.mooc.offline.entity.course.course_detail.course_files.FileInformationEntity;
import com.begoit.mooc.offline.entity.course.course_detail.course_files.PreCourseEntity;
import com.begoit.mooc.offline.entity.course.course_detail.course_files.PreCourseGroupEntity;
import com.begoit.mooc.offline.entity.course.course_detail.course_files.VideonobEntity;
import com.begoit.mooc.offline.entity.course.course_detail.course_files.VideoTestEntity;
import com.begoit.mooc.offline.entity.course.course_list.CourseListEntity;
import com.begoit.mooc.offline.entity.course.course_list.CourseListItemPreImgPlaceHolderEntity;
import com.begoit.mooc.offline.entity.course.learning_space.HistoryCourseEntity;
import com.begoit.mooc.offline.entity.course.teacher.TeacherConfigEntity;
import com.begoit.mooc.offline.entity.course.teacher.TeacherEntity;
import com.begoit.mooc.offline.entity.course.user_download.AppLogEntity;
import com.begoit.mooc.offline.entity.course.user_download.CourseDownLoadedEntity;
import com.begoit.mooc.offline.entity.course.user_download.CourseRegistrationEntity;
import com.begoit.mooc.offline.entity.course.user_download.UserChannelEntity;
import com.begoit.mooc.offline.entity.course.user_download.VideoTestLogEntity;
import com.begoit.mooc.offline.entity.course.user_download.VideoTestScoreEntity;
import com.begoit.mooc.offline.entity.kindMenu.MenuItemEntity;
import com.begoit.mooc.offline.entity.user.UserEntity;

import com.begoit.mooc.db.CourseDetailEntityDao;
import com.begoit.mooc.db.ArticelEntityDao;
import com.begoit.mooc.db.ArticleClassEntityDao;
import com.begoit.mooc.db.CourseDetailFilesEntityDao;
import com.begoit.mooc.db.FileInformationEntityDao;
import com.begoit.mooc.db.PreCourseEntityDao;
import com.begoit.mooc.db.PreCourseGroupEntityDao;
import com.begoit.mooc.db.VideonobEntityDao;
import com.begoit.mooc.db.VideoTestEntityDao;
import com.begoit.mooc.db.CourseListEntityDao;
import com.begoit.mooc.db.CourseListItemPreImgPlaceHolderEntityDao;
import com.begoit.mooc.db.HistoryCourseEntityDao;
import com.begoit.mooc.db.TeacherConfigEntityDao;
import com.begoit.mooc.db.TeacherEntityDao;
import com.begoit.mooc.db.AppLogEntityDao;
import com.begoit.mooc.db.CourseDownLoadedEntityDao;
import com.begoit.mooc.db.CourseRegistrationEntityDao;
import com.begoit.mooc.db.UserChannelEntityDao;
import com.begoit.mooc.db.VideoTestLogEntityDao;
import com.begoit.mooc.db.VideoTestScoreEntityDao;
import com.begoit.mooc.db.MenuItemEntityDao;
import com.begoit.mooc.db.UserEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig courseDetailEntityDaoConfig;
    private final DaoConfig articelEntityDaoConfig;
    private final DaoConfig articleClassEntityDaoConfig;
    private final DaoConfig courseDetailFilesEntityDaoConfig;
    private final DaoConfig fileInformationEntityDaoConfig;
    private final DaoConfig preCourseEntityDaoConfig;
    private final DaoConfig preCourseGroupEntityDaoConfig;
    private final DaoConfig videonobEntityDaoConfig;
    private final DaoConfig videoTestEntityDaoConfig;
    private final DaoConfig courseListEntityDaoConfig;
    private final DaoConfig courseListItemPreImgPlaceHolderEntityDaoConfig;
    private final DaoConfig historyCourseEntityDaoConfig;
    private final DaoConfig teacherConfigEntityDaoConfig;
    private final DaoConfig teacherEntityDaoConfig;
    private final DaoConfig appLogEntityDaoConfig;
    private final DaoConfig courseDownLoadedEntityDaoConfig;
    private final DaoConfig courseRegistrationEntityDaoConfig;
    private final DaoConfig userChannelEntityDaoConfig;
    private final DaoConfig videoTestLogEntityDaoConfig;
    private final DaoConfig videoTestScoreEntityDaoConfig;
    private final DaoConfig menuItemEntityDaoConfig;
    private final DaoConfig userEntityDaoConfig;

    private final CourseDetailEntityDao courseDetailEntityDao;
    private final ArticelEntityDao articelEntityDao;
    private final ArticleClassEntityDao articleClassEntityDao;
    private final CourseDetailFilesEntityDao courseDetailFilesEntityDao;
    private final FileInformationEntityDao fileInformationEntityDao;
    private final PreCourseEntityDao preCourseEntityDao;
    private final PreCourseGroupEntityDao preCourseGroupEntityDao;
    private final VideonobEntityDao videonobEntityDao;
    private final VideoTestEntityDao videoTestEntityDao;
    private final CourseListEntityDao courseListEntityDao;
    private final CourseListItemPreImgPlaceHolderEntityDao courseListItemPreImgPlaceHolderEntityDao;
    private final HistoryCourseEntityDao historyCourseEntityDao;
    private final TeacherConfigEntityDao teacherConfigEntityDao;
    private final TeacherEntityDao teacherEntityDao;
    private final AppLogEntityDao appLogEntityDao;
    private final CourseDownLoadedEntityDao courseDownLoadedEntityDao;
    private final CourseRegistrationEntityDao courseRegistrationEntityDao;
    private final UserChannelEntityDao userChannelEntityDao;
    private final VideoTestLogEntityDao videoTestLogEntityDao;
    private final VideoTestScoreEntityDao videoTestScoreEntityDao;
    private final MenuItemEntityDao menuItemEntityDao;
    private final UserEntityDao userEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        courseDetailEntityDaoConfig = daoConfigMap.get(CourseDetailEntityDao.class).clone();
        courseDetailEntityDaoConfig.initIdentityScope(type);

        articelEntityDaoConfig = daoConfigMap.get(ArticelEntityDao.class).clone();
        articelEntityDaoConfig.initIdentityScope(type);

        articleClassEntityDaoConfig = daoConfigMap.get(ArticleClassEntityDao.class).clone();
        articleClassEntityDaoConfig.initIdentityScope(type);

        courseDetailFilesEntityDaoConfig = daoConfigMap.get(CourseDetailFilesEntityDao.class).clone();
        courseDetailFilesEntityDaoConfig.initIdentityScope(type);

        fileInformationEntityDaoConfig = daoConfigMap.get(FileInformationEntityDao.class).clone();
        fileInformationEntityDaoConfig.initIdentityScope(type);

        preCourseEntityDaoConfig = daoConfigMap.get(PreCourseEntityDao.class).clone();
        preCourseEntityDaoConfig.initIdentityScope(type);

        preCourseGroupEntityDaoConfig = daoConfigMap.get(PreCourseGroupEntityDao.class).clone();
        preCourseGroupEntityDaoConfig.initIdentityScope(type);

        videonobEntityDaoConfig = daoConfigMap.get(VideonobEntityDao.class).clone();
        videonobEntityDaoConfig.initIdentityScope(type);

        videoTestEntityDaoConfig = daoConfigMap.get(VideoTestEntityDao.class).clone();
        videoTestEntityDaoConfig.initIdentityScope(type);

        courseListEntityDaoConfig = daoConfigMap.get(CourseListEntityDao.class).clone();
        courseListEntityDaoConfig.initIdentityScope(type);

        courseListItemPreImgPlaceHolderEntityDaoConfig = daoConfigMap.get(CourseListItemPreImgPlaceHolderEntityDao.class).clone();
        courseListItemPreImgPlaceHolderEntityDaoConfig.initIdentityScope(type);

        historyCourseEntityDaoConfig = daoConfigMap.get(HistoryCourseEntityDao.class).clone();
        historyCourseEntityDaoConfig.initIdentityScope(type);

        teacherConfigEntityDaoConfig = daoConfigMap.get(TeacherConfigEntityDao.class).clone();
        teacherConfigEntityDaoConfig.initIdentityScope(type);

        teacherEntityDaoConfig = daoConfigMap.get(TeacherEntityDao.class).clone();
        teacherEntityDaoConfig.initIdentityScope(type);

        appLogEntityDaoConfig = daoConfigMap.get(AppLogEntityDao.class).clone();
        appLogEntityDaoConfig.initIdentityScope(type);

        courseDownLoadedEntityDaoConfig = daoConfigMap.get(CourseDownLoadedEntityDao.class).clone();
        courseDownLoadedEntityDaoConfig.initIdentityScope(type);

        courseRegistrationEntityDaoConfig = daoConfigMap.get(CourseRegistrationEntityDao.class).clone();
        courseRegistrationEntityDaoConfig.initIdentityScope(type);

        userChannelEntityDaoConfig = daoConfigMap.get(UserChannelEntityDao.class).clone();
        userChannelEntityDaoConfig.initIdentityScope(type);

        videoTestLogEntityDaoConfig = daoConfigMap.get(VideoTestLogEntityDao.class).clone();
        videoTestLogEntityDaoConfig.initIdentityScope(type);

        videoTestScoreEntityDaoConfig = daoConfigMap.get(VideoTestScoreEntityDao.class).clone();
        videoTestScoreEntityDaoConfig.initIdentityScope(type);

        menuItemEntityDaoConfig = daoConfigMap.get(MenuItemEntityDao.class).clone();
        menuItemEntityDaoConfig.initIdentityScope(type);

        userEntityDaoConfig = daoConfigMap.get(UserEntityDao.class).clone();
        userEntityDaoConfig.initIdentityScope(type);

        courseDetailEntityDao = new CourseDetailEntityDao(courseDetailEntityDaoConfig, this);
        articelEntityDao = new ArticelEntityDao(articelEntityDaoConfig, this);
        articleClassEntityDao = new ArticleClassEntityDao(articleClassEntityDaoConfig, this);
        courseDetailFilesEntityDao = new CourseDetailFilesEntityDao(courseDetailFilesEntityDaoConfig, this);
        fileInformationEntityDao = new FileInformationEntityDao(fileInformationEntityDaoConfig, this);
        preCourseEntityDao = new PreCourseEntityDao(preCourseEntityDaoConfig, this);
        preCourseGroupEntityDao = new PreCourseGroupEntityDao(preCourseGroupEntityDaoConfig, this);
        videonobEntityDao = new VideonobEntityDao(videonobEntityDaoConfig, this);
        videoTestEntityDao = new VideoTestEntityDao(videoTestEntityDaoConfig, this);
        courseListEntityDao = new CourseListEntityDao(courseListEntityDaoConfig, this);
        courseListItemPreImgPlaceHolderEntityDao = new CourseListItemPreImgPlaceHolderEntityDao(courseListItemPreImgPlaceHolderEntityDaoConfig, this);
        historyCourseEntityDao = new HistoryCourseEntityDao(historyCourseEntityDaoConfig, this);
        teacherConfigEntityDao = new TeacherConfigEntityDao(teacherConfigEntityDaoConfig, this);
        teacherEntityDao = new TeacherEntityDao(teacherEntityDaoConfig, this);
        appLogEntityDao = new AppLogEntityDao(appLogEntityDaoConfig, this);
        courseDownLoadedEntityDao = new CourseDownLoadedEntityDao(courseDownLoadedEntityDaoConfig, this);
        courseRegistrationEntityDao = new CourseRegistrationEntityDao(courseRegistrationEntityDaoConfig, this);
        userChannelEntityDao = new UserChannelEntityDao(userChannelEntityDaoConfig, this);
        videoTestLogEntityDao = new VideoTestLogEntityDao(videoTestLogEntityDaoConfig, this);
        videoTestScoreEntityDao = new VideoTestScoreEntityDao(videoTestScoreEntityDaoConfig, this);
        menuItemEntityDao = new MenuItemEntityDao(menuItemEntityDaoConfig, this);
        userEntityDao = new UserEntityDao(userEntityDaoConfig, this);

        registerDao(CourseDetailEntity.class, courseDetailEntityDao);
        registerDao(ArticelEntity.class, articelEntityDao);
        registerDao(ArticleClassEntity.class, articleClassEntityDao);
        registerDao(CourseDetailFilesEntity.class, courseDetailFilesEntityDao);
        registerDao(FileInformationEntity.class, fileInformationEntityDao);
        registerDao(PreCourseEntity.class, preCourseEntityDao);
        registerDao(PreCourseGroupEntity.class, preCourseGroupEntityDao);
        registerDao(VideonobEntity.class, videonobEntityDao);
        registerDao(VideoTestEntity.class, videoTestEntityDao);
        registerDao(CourseListEntity.class, courseListEntityDao);
        registerDao(CourseListItemPreImgPlaceHolderEntity.class, courseListItemPreImgPlaceHolderEntityDao);
        registerDao(HistoryCourseEntity.class, historyCourseEntityDao);
        registerDao(TeacherConfigEntity.class, teacherConfigEntityDao);
        registerDao(TeacherEntity.class, teacherEntityDao);
        registerDao(AppLogEntity.class, appLogEntityDao);
        registerDao(CourseDownLoadedEntity.class, courseDownLoadedEntityDao);
        registerDao(CourseRegistrationEntity.class, courseRegistrationEntityDao);
        registerDao(UserChannelEntity.class, userChannelEntityDao);
        registerDao(VideoTestLogEntity.class, videoTestLogEntityDao);
        registerDao(VideoTestScoreEntity.class, videoTestScoreEntityDao);
        registerDao(MenuItemEntity.class, menuItemEntityDao);
        registerDao(UserEntity.class, userEntityDao);
    }
    
    public void clear() {
        courseDetailEntityDaoConfig.clearIdentityScope();
        articelEntityDaoConfig.clearIdentityScope();
        articleClassEntityDaoConfig.clearIdentityScope();
        courseDetailFilesEntityDaoConfig.clearIdentityScope();
        fileInformationEntityDaoConfig.clearIdentityScope();
        preCourseEntityDaoConfig.clearIdentityScope();
        preCourseGroupEntityDaoConfig.clearIdentityScope();
        videonobEntityDaoConfig.clearIdentityScope();
        videoTestEntityDaoConfig.clearIdentityScope();
        courseListEntityDaoConfig.clearIdentityScope();
        courseListItemPreImgPlaceHolderEntityDaoConfig.clearIdentityScope();
        historyCourseEntityDaoConfig.clearIdentityScope();
        teacherConfigEntityDaoConfig.clearIdentityScope();
        teacherEntityDaoConfig.clearIdentityScope();
        appLogEntityDaoConfig.clearIdentityScope();
        courseDownLoadedEntityDaoConfig.clearIdentityScope();
        courseRegistrationEntityDaoConfig.clearIdentityScope();
        userChannelEntityDaoConfig.clearIdentityScope();
        videoTestLogEntityDaoConfig.clearIdentityScope();
        videoTestScoreEntityDaoConfig.clearIdentityScope();
        menuItemEntityDaoConfig.clearIdentityScope();
        userEntityDaoConfig.clearIdentityScope();
    }

    public CourseDetailEntityDao getCourseDetailEntityDao() {
        return courseDetailEntityDao;
    }

    public ArticelEntityDao getArticelEntityDao() {
        return articelEntityDao;
    }

    public ArticleClassEntityDao getArticleClassEntityDao() {
        return articleClassEntityDao;
    }

    public CourseDetailFilesEntityDao getCourseDetailFilesEntityDao() {
        return courseDetailFilesEntityDao;
    }

    public FileInformationEntityDao getFileInformationEntityDao() {
        return fileInformationEntityDao;
    }

    public PreCourseEntityDao getPreCourseEntityDao() {
        return preCourseEntityDao;
    }

    public PreCourseGroupEntityDao getPreCourseGroupEntityDao() {
        return preCourseGroupEntityDao;
    }

    public VideonobEntityDao getVideonobEntityDao() {
        return videonobEntityDao;
    }

    public VideoTestEntityDao getVideoTestEntityDao() {
        return videoTestEntityDao;
    }

    public CourseListEntityDao getCourseListEntityDao() {
        return courseListEntityDao;
    }

    public CourseListItemPreImgPlaceHolderEntityDao getCourseListItemPreImgPlaceHolderEntityDao() {
        return courseListItemPreImgPlaceHolderEntityDao;
    }

    public HistoryCourseEntityDao getHistoryCourseEntityDao() {
        return historyCourseEntityDao;
    }

    public TeacherConfigEntityDao getTeacherConfigEntityDao() {
        return teacherConfigEntityDao;
    }

    public TeacherEntityDao getTeacherEntityDao() {
        return teacherEntityDao;
    }

    public AppLogEntityDao getAppLogEntityDao() {
        return appLogEntityDao;
    }

    public CourseDownLoadedEntityDao getCourseDownLoadedEntityDao() {
        return courseDownLoadedEntityDao;
    }

    public CourseRegistrationEntityDao getCourseRegistrationEntityDao() {
        return courseRegistrationEntityDao;
    }

    public UserChannelEntityDao getUserChannelEntityDao() {
        return userChannelEntityDao;
    }

    public VideoTestLogEntityDao getVideoTestLogEntityDao() {
        return videoTestLogEntityDao;
    }

    public VideoTestScoreEntityDao getVideoTestScoreEntityDao() {
        return videoTestScoreEntityDao;
    }

    public MenuItemEntityDao getMenuItemEntityDao() {
        return menuItemEntityDao;
    }

    public UserEntityDao getUserEntityDao() {
        return userEntityDao;
    }

}
