package com.begoit.mooc.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.begoit.mooc.offline.entity.course.course_detail.course_files.PreCourseEntity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "PRE_COURSE_ENTITY".
*/
public class PreCourseEntityDao extends AbstractDao<PreCourseEntity, String> {

    public static final String TABLENAME = "PRE_COURSE_ENTITY";

    /**
     * Properties of entity PreCourseEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property ChannelId = new Property(0, String.class, "channelId", true, "CHANNEL_ID");
    }

    private DaoSession daoSession;


    public PreCourseEntityDao(DaoConfig config) {
        super(config);
    }
    
    public PreCourseEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"PRE_COURSE_ENTITY\" (" + //
                "\"CHANNEL_ID\" TEXT PRIMARY KEY NOT NULL );"); // 0: channelId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"PRE_COURSE_ENTITY\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, PreCourseEntity entity) {
        stmt.clearBindings();
 
        String channelId = entity.getChannelId();
        if (channelId != null) {
            stmt.bindString(1, channelId);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, PreCourseEntity entity) {
        stmt.clearBindings();
 
        String channelId = entity.getChannelId();
        if (channelId != null) {
            stmt.bindString(1, channelId);
        }
    }

    @Override
    protected final void attachEntity(PreCourseEntity entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    @Override
    public PreCourseEntity readEntity(Cursor cursor, int offset) {
        PreCourseEntity entity = new PreCourseEntity( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0) // channelId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, PreCourseEntity entity, int offset) {
        entity.setChannelId(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
     }
    
    @Override
    protected final String updateKeyAfterInsert(PreCourseEntity entity, long rowId) {
        return entity.getChannelId();
    }
    
    @Override
    public String getKey(PreCourseEntity entity) {
        if(entity != null) {
            return entity.getChannelId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(PreCourseEntity entity) {
        return entity.getChannelId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
