package com.begoit.mooc.db;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.SqlUtils;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.query.Query;
import org.greenrobot.greendao.query.QueryBuilder;

import com.begoit.mooc.offline.entity.course.teacher.TeacherEntity;

import com.begoit.mooc.offline.entity.course.teacher.TeacherConfigEntity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TEACHER_CONFIG_ENTITY".
*/
public class TeacherConfigEntityDao extends AbstractDao<TeacherConfigEntity, String> {

    public static final String TABLENAME = "TEACHER_CONFIG_ENTITY";

    /**
     * Properties of entity TeacherConfigEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, String.class, "id", true, "ID");
        public final static Property ChannelId = new Property(1, String.class, "channelId", false, "CHANNEL_ID");
        public final static Property TeacherId = new Property(2, String.class, "teacherId", false, "TEACHER_ID");
    }

    private DaoSession daoSession;

    private Query<TeacherConfigEntity> courseDetailEntity_TeacherConfigQuery;

    public TeacherConfigEntityDao(DaoConfig config) {
        super(config);
    }
    
    public TeacherConfigEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"TEACHER_CONFIG_ENTITY\" (" + //
                "\"ID\" TEXT PRIMARY KEY NOT NULL ," + // 0: id
                "\"CHANNEL_ID\" TEXT," + // 1: channelId
                "\"TEACHER_ID\" TEXT);"); // 2: teacherId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TEACHER_CONFIG_ENTITY\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, TeacherConfigEntity entity) {
        stmt.clearBindings();
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(1, id);
        }
 
        String channelId = entity.getChannelId();
        if (channelId != null) {
            stmt.bindString(2, channelId);
        }
 
        String teacherId = entity.getTeacherId();
        if (teacherId != null) {
            stmt.bindString(3, teacherId);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, TeacherConfigEntity entity) {
        stmt.clearBindings();
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(1, id);
        }
 
        String channelId = entity.getChannelId();
        if (channelId != null) {
            stmt.bindString(2, channelId);
        }
 
        String teacherId = entity.getTeacherId();
        if (teacherId != null) {
            stmt.bindString(3, teacherId);
        }
    }

    @Override
    protected final void attachEntity(TeacherConfigEntity entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    @Override
    public TeacherConfigEntity readEntity(Cursor cursor, int offset) {
        TeacherConfigEntity entity = new TeacherConfigEntity( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // channelId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // teacherId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, TeacherConfigEntity entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setChannelId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setTeacherId(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    @Override
    protected final String updateKeyAfterInsert(TeacherConfigEntity entity, long rowId) {
        return entity.getId();
    }
    
    @Override
    public String getKey(TeacherConfigEntity entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(TeacherConfigEntity entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "teacherConfig" to-many relationship of CourseDetailEntity. */
    public List<TeacherConfigEntity> _queryCourseDetailEntity_TeacherConfig(String channelId) {
        synchronized (this) {
            if (courseDetailEntity_TeacherConfigQuery == null) {
                QueryBuilder<TeacherConfigEntity> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.ChannelId.eq(null));
                courseDetailEntity_TeacherConfigQuery = queryBuilder.build();
            }
        }
        Query<TeacherConfigEntity> query = courseDetailEntity_TeacherConfigQuery.forCurrentThread();
        query.setParameter(0, channelId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getTeacherEntityDao().getAllColumns());
            builder.append(" FROM TEACHER_CONFIG_ENTITY T");
            builder.append(" LEFT JOIN TEACHER_ENTITY T0 ON T.\"TEACHER_ID\"=T0.\"ID\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected TeacherConfigEntity loadCurrentDeep(Cursor cursor, boolean lock) {
        TeacherConfigEntity entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        TeacherEntity teachers = loadCurrentOther(daoSession.getTeacherEntityDao(), cursor, offset);
        entity.setTeachers(teachers);

        return entity;    
    }

    public TeacherConfigEntity loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<TeacherConfigEntity> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<TeacherConfigEntity> list = new ArrayList<TeacherConfigEntity>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<TeacherConfigEntity> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<TeacherConfigEntity> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
